### ISSUE TITLE
fizzbuzz feedback

### ISSUE THREAD

**Issue by mathematicalmichael** [jordanrhall/educational-fun#1]
only one line printed per loop, so just rethink where your newlines are; you dont need to pad printouts with empty lines, this just makes for extraneous scrolling. 

you leveraged the least common multiple by checking that first. good. 

but now, if I asked you to switch to 7 and 2 instead of 5 and 3, you have to change code on three different lines. 

do we _really_ need three if statements?

**Comment by mathematicalmichael** [comment]
related to the last comment: imagine your boss comes to you and says 

> oh, and if div by 4, throw "bizz" into the mix 
> i.e., fizzbizzbuzz is the longest string now

how can we do some work now to make an uncertain number of future "feature requests" easy to address? attempt to minimize the number of lines of code that need to change.

**Comment by jordanrhall** [comment]
Thanks for the suggestions and help, Michael! A function abstracting this process was the way to go.
