### ISSUE TITLE
some helpful repos

### ISSUE THREAD

**Issue by mathematicalmichael** [jordanrhall/educational-fun#2]
Hey J.

I discovered some repos that may be of help to you

Lots of algorithms implemented
https://github.com/TheAlgorithms/Python

set up AWS development environment locally to learn the stack while avoiding paying the piper (i'll be deploying this on `carme` sometime soon-ish and could give you access)
https://github.com/localstack/localstack

other neatness:
algorithmic trading: https://www.zipline.io / https://github.com/quantopian/zipline
secure remote-computer communication: https://github.com/fabric/fabric

**Comment by mathematicalmichael** [comment]
I discovered these by playing https://stripcode.dev for like fifteen minutes. super neat: https://www.youtube.com/watch?v=pXDM5CA47Mg

watching that video lets you see behind the curtain of how apps are set up. His videos/repos are quite good learning tools.

**Comment by mathematicalmichael** [comment]
another one: https://github.com/ml-tooling/best-of-ml-python

**Comment by jordanrhall** [comment]
Thank you so much! This will be really helpful for me, and maybe even some of my other buddies who I've pulled in as contributors on this repo!

**Comment by jordanrhall** [comment]
Closing this issue. @CarterWPAnkele and @prose11 - you will still be able to refer to these links by viewing our "closed issues."
