### ISSUE TITLE
Check that inputs are integers in Cake Sale Challenge

### ISSUE THREAD

**Issue by jordanrhall** [jordanrhall/educational-fun#8]
First off -- nice first draft of this challenge, Cart! I ran it locally with success ... however, when I passed non-integer inputs, the script failed.

Beginning in line 12 of the cake sale script, you are casting inputs as integers -- not so different than your Number_Guesser. If you recall, in your Number_Guesser script, you had some basic checks to make sure inputs were actually numbers. I would just hack that basic structure and apply here.

Links to line 12:
https://github.com/jordanrhall/educational-fun/blob/efdc163ce7b11eff98da402a2bfaec4cc349244b/Cake_Sale_Challenge.py#L12

**Comment by CarterWPAnkele** [comment]
Issue has ben resolved
